name: package
on: [push]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '>= 1.17'
      - uses: actions/setup-node@v3
        with:
          node-version: '>= 16'
      - run: make build
      - run: ls -lR .
